bundle/nxiq-operator-certified.clusterserviceversion.yaml
deploy/olm-catalog/nxiq-operator-certified/manifests/nxiq-operator-certified.clusterserviceversion.yaml

Complete copy to display in the OpenShift operator hub.
JIRA: https://issues.sonatype.org/browse/INT-2881

INT-2881 finalize operatorhub docs

---

Jenkinsfile
build/Dockerfile
ci/TriggerRedHatBuild.groovy
deploy/crds/sonatype.com_v1alpha1_nexusiq_cr.yaml
deploy/olm-catalog/nxiq-operator-certified/1.94.0-1/nxiq-operator-certified.v1.94.0-1.clusterserviceversion.yaml
deploy/olm-catalog/nxiq-operator-certified/nxiq-operator-certified.package.yaml
deploy/operator.yaml
helm-charts/iqserver/Chart.yaml
helm-charts/iqserver/values.yaml

Jenkins and Red Hat builds for iq server's operator.
JIRA: https://issues.sonatype.org/browse/INT-2547
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/operator-iq/job/feature-snapshots/job/INT-2547-jenkins/

INT-2547 jenkins build for operator for iq server

---

build/Dockerfile
deploy/crds/sonatype.com_v1alpha1_nexusiq_cr.yaml
deploy/olm-catalog/nxiq-operator-certified/1.95.0-1/nxiq-operator-certified.v1.95.0-1.clusterserviceversion.yaml
deploy/olm-catalog/nxiq-operator-certified/1.96.0-1/nxiq-operator-certified.v1.96.0-1.clusterserviceversion.yaml
deploy/olm-catalog/nxiq-operator-certified/nxiq-operator-certified.package.yaml
deploy/operator.yaml
helm-charts/iqserver/Chart.yaml
helm-charts/iqserver/templates/NOTES.txt
helm-charts/iqserver/templates/deployment.yaml
helm-charts/iqserver/templates/service.yaml
helm-charts/iqserver/values.yaml

upgrade to latest helm charts and bump to latest iq version.
JIRA: https://issues.sonatype.org/browse/INT-3123
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/operator-iq/job/feature-snapshots/job/INT-3123-upgrade-charts/

INT-3123 upgrade charts and iq version

---

ci/TriggerRedHatBuild.groovy
scripts/new_version.sh
scripts/templates/Chart.yaml
scripts/templates/Dockerfile
scripts/templates/nxiq-operator-certified.package.yaml
scripts/templates/nxiq-operator-certified.vX.X.X-X.clusterserviceversion.yaml
scripts/templates/operator.yaml
scripts/templates/sonatype.com_v1alpha1_nexusiq_cr.yaml
scripts/templates/values.yaml

I don't want to need to carefully update the operator for every new version of the server.

template version updates

---

build/Dockerfile
deploy/crds/sonatype.com_v1alpha1_nexusiq_cr.yaml
deploy/olm-catalog/nxiq-operator-certified/1.97.0-1/nxiq-operator-certified.v1.97.0-1.clusterserviceversion.yaml
deploy/olm-catalog/nxiq-operator-certified/nxiq-operator-certified.package.yaml
deploy/operator.yaml
helm-charts/iqserver/Chart.yaml
helm-charts/iqserver/values.yaml

automatically generated by script.
JIRA: https://issues.sonatype.org/browse/INT-3325

INT-3325 upgrade to iq 1.97.0

---

build/Dockerfile
deploy/crds/sonatype.com_v1alpha1_nexusiq_cr.yaml
deploy/olm-catalog/nxiq-operator-certified/1.98.0-1/nxiq-operator-certified.v1.98.0-1.clusterserviceversion.yaml
deploy/olm-catalog/nxiq-operator-certified/nxiq-operator-certified.package.yaml
deploy/operator.yaml
helm-charts/iqserver/Chart.yaml
helm-charts/iqserver/values.yaml

jira: https://issues.sonatype.org/browse/INT-3501
build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/operator-iq/job/feature-snapshots/job/INT-3501-upgrade-1.98.0/

INT-3501 upgrade to IQ 1.98.0

---

build/Dockerfile
deploy/crds/sonatype.com_v1alpha1_nexusiq_cr.yaml
deploy/olm-catalog/nxiq-operator-certified/1.99.0-1/nxiq-operator-certified.v1.99.0-1.clusterserviceversion.yaml
deploy/olm-catalog/nxiq-operator-certified/nxiq-operator-certified.package.yaml
deploy/operator.yaml
helm-charts/iqserver/Chart.yaml
helm-charts/iqserver/values.yaml

INT-3564 upgrade to IQ 1.99.0

---

deploy/olm-catalog/nxiq-operator-certified/1.100.0-2/nxiq-operator-certified.v1.100.0-2.clusterserviceversion.yaml
scripts/bundle.sh

create and push an operator bundle just like nxrm operator does. (same script as reviewed for nxrm operator.)
JIRA: https://issues.sonatype.org/browse/INT-4424
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/operator-iq/job/feature-snapshots/job/INT-4424-bundling/

INT-4424 new bundle image

---

Jenkinsfile

simple maintenance update, so merging immediately.

update to newest jenkins libs

---

build/Dockerfile
deploy/crds/sonatype.com_v1alpha1_nexusiq_cr.yaml
deploy/olm-catalog/nxiq-operator-certified/1.108.0-1/nxiq-operator-certified.v1.108.0-1.clusterserviceversion.yaml
deploy/olm-catalog/nxiq-operator-certified/nxiq-operator-certified.package.yaml
deploy/operator.yaml
helm-charts/iqserver/Chart.yaml
helm-charts/iqserver/values.yaml

mechanical update to new IQ version 108.
JIRA: https://issues.sonatype.org/browse/INT-4823
Jenkins: https://jenkins.ci.sonatype.dev/view/all/job/integrations/job/cloud/job/operator-iq/job/feature-snapshots/job/INT-4823-ship-IQ-108/

INT-4823 scripted update to IQ 108 versions

---

Jenkinsfile

Github Default Branch Migration - RedHat Operator - IQ
jira: https://issues.sonatype.org/browse/INT-5495 
Jenkins: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/operator-iq/job/feature-snapshots/job/INT-5495-git-branch-migration/1/

INT-5495 | Github Default Branch Migration - RedHat Operator - IQ

---

scripts/install.sh
scripts/templates/nxiq-operator-certified.vX.X.X-X.clusterserviceversion.yaml
scripts/templates/sonatype.com_v1alpha1_nexusiq_cr.yaml
scripts/templates/values.yaml

Configure debug logging and files, so support can find them.
JIRA: https://issues.sonatype.org/browse/INT-5072
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/operator-iq/job/feature-snapshots/job/INT-5072-configure-logging/

INT-5072 configure logging

---

scripts/new_version.sh
scripts/templates/Chart.yaml
scripts/templates/annotations.yaml
scripts/templates/nxiq-operator-certified.clusterserviceversion.yaml
scripts/templates/nxiq-operator-certified.package.yaml
scripts/templates/operator.yaml
scripts/templates/sonatype.com_nexusiqs_crd.yaml
scripts/templates/sonatype.com_v1alpha1_nexusiq_cr.yaml
scripts/templates/values.yaml

Script and templates now produce image and bundle metadata in the newest format that can be submitted to Red Hat.
JIRA: https://issues.sonatype.org/browse/INT-6317

INT-6317 update for red hat

---

deploy/crds/sonatype.com_v1alpha1_nexusiq_cr.yaml
deploy/olm-catalog/nxiq-operator-certified/1.128.0-1/manifests/nxiq-operator-certified.clusterserviceversion.yaml
deploy/olm-catalog/nxiq-operator-certified/1.128.0-1/manifests/sonatype.com_nexusiqs_crd.yaml
deploy/olm-catalog/nxiq-operator-certified/1.128.0-1/metadata/annotations.yaml
deploy/olm-catalog/nxiq-operator-certified/nxiq-operator-certified.package.yaml
deploy/operator.yaml
helm-charts/iqserver/Chart.yaml
helm-charts/iqserver/values.yaml
scripts/new_version.sh
scripts/templates/Chart.yaml
scripts/templates/annotations.yaml
scripts/templates/nxiq-operator-certified.clusterserviceversion.yaml
scripts/templates/nxiq-operator-certified.package.yaml
scripts/templates/operator.yaml
scripts/templates/sonatype.com_nexusiqs_crd.yaml
scripts/templates/sonatype.com_v1alpha1_nexusiq_cr.yaml
scripts/templates/values.yaml

The bundle matches deployed bundle at red hat and it was produced by the new scrip and templates. this serves as proof that the other PR is correct.
JIRA: https://issues.sonatype.org/browse/INT-6317

INT-6317 rebuild 1.128.0-1

---

scripts/templates/nxiq-operator-certified.clusterserviceversion.yaml

Updating docs to add Operator Installation Suggestion to handle unscheduled downtime due to new operator releases.
JIRA: https://issues.sonatype.org/browse/INT-6772

INT-6772 Adding Operator Intallation Suggestion

---

.gitignore
Jenkinsfile
build_red_hat_image.sh

build, push, and certify the iq operator with red hat.
JIRA: https://issues.sonatype.org/browse/INT-6886
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Red%20Hat/job/operator-iq-release/

INT-6886 new build, push, and certify for iq operator

---

helm-charts/iqserver/templates/configmap.yaml
helm-charts/iqserver/templates/deployment.yaml
helm-charts/iqserver/templates/persistentVolume.yaml
helm-charts/iqserver/templates/persistentVolumeClaim.yaml
scripts/templates/nxiq-operator-certified.clusterserviceversion.yaml
scripts/templates/sonatype.com_v1alpha1_nexusiq_cr.yaml
scripts/templates/values.yaml

Allow user to inject trusted certificates for their own certificate authorities.
JIRA: https://issues.sonatype.org/browse/INT-6832
Build: N/A

INT-6832 configmap for CA

---

scripts/templates/Dockerfile

use new helm-operator.
JIRA: https://issues.sonatype.org/browse/INT-7378

INT-7378 upgrade to helm operator 1.24.0

---

README.md

Updating some instructions and providing examples.

Update in README

---

Jenkinsfile
build_red_hat_image.sh

Switch to quay.io for certification.
JIRA: https://issues.sonatype.org/browse/INT-7341
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Red%20Hat/job/release-test/3/
similar to other PRs for this ticket.

INT-7341 switch to quay.io repo for cert

---

helm-charts/iqserver/templates/deployment.yaml
scripts/templates/operator.yaml

alleviate the new security warnings with newer k8s/openshift.
JIRA: https://issues.sonatype.org/browse/INT-7432

INT-7432 ensure unprivileged execution

---

README.md

better urls in docs to find versions
